name: Deploy

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
      cloudflare:
        required: false
        type: boolean
        default: false
    secrets:
      firebase-token:
        required: true
      cloudflare-token:
        required: false
      cloudflare-account-id:
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: ${{ github.ref_type == 'tag' && 1 || 0 }}

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - run: npm ci

      - run: npm ci
        working-directory: functions

      - name: Set env
        run: |
          echo "REACT_APP_VERSION=$(git describe --tags HEAD|sed s/^v//)" >> $GITHUB_ENV

      - run: npm run build:${{ inputs.env }}

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: >-
            deploy
            -P ${{ inputs.env }}
            --only database,functions${{ !inputs.cloudflare && ',hosting' || '' }}
        env:
          FIREBASE_TOKEN: ${{ secrets.firebase-token }}

      - name: Deploy to Cloudflare
        if: inputs.cloudflare
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.cloudflare-token }}
          accountId: ${{ secrets.cloudflare-account-id }}
          wranglerVersion: "4.65.0"
          command: deploy
